root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  no-console: 2
  '@typescript-eslint/no-inferrable-types': 2
  comma-dangle:
    - error
    - arrays: never
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  indent:
    - error
    - 2
  object-curly-spacing:
    - 2
    - always
  array-bracket-spacing:
    - 2
    - always
  curly:
    - 2
    - all
  no-trailing-spaces:
    - 2
  semi:
    - 2
    - never
  object-curly-newline:
    - 2
    - multiline: true
      minProperties: 2
      consistent: true
  object-property-newline:
    - 2
  prefer-arrow-callback:
    - 2
  prefer-const:
    - 2
  object-shorthand:
    - 2
  no-param-reassign:
    - 2
    - props: false
  no-extra-parens:
    - 2